version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    networks:
      - graylog

  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=S3cur3P@ssw0rd-Opensearch!
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - graylog

  graylog:
    image: graylog/graylog:5.2
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=foyUCRVvXZbjJtJWBsXiPghD5bTWvS4XdqjqyKk0lo88Hqp9QcDKUAUeQdJW40oQ7hSitOXRPk22cIdcyTkVmt4Dhigj0cHB
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://<graylog-ip>:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
      - GRAYLOG_MONGODB_URI=mongodb://mongo:27017/graylog
      - GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE=100mb
    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 -- /docker-entrypoint.sh
    depends_on:
      - mongo
      - opensearch
    ports:
      - "9000:9000"      # Web UI
      - "7007:7007/udp"  # Syslog UDP
      - "1514:1514/udp"  # Syslog UDP
      - "1514:1514/tcp"  # Syslog TCP
    networks:
      - graylog

networks:
  graylog:
    driver: bridge

